config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  
  get 'dbmap', to: 'static_pages#dbmap'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get '/order_lists/:id/copy_set', to: 'order_lists#copy_set', as: 'copy_set_order_list'
  post '/order_lists/:id/copy', to: 'order_lists#copy', as: 'copy_order_list'
  
  get 'signup', to: 'users#new'
  resources :users
  
  resources :order_lists, only: [:index, :show, :create, :edit, :update, :destroy] do
    member do
      get :line_items
    end
  end
  
  resources :orders, only: [:index, :show, :create, :edit, :update, :destroy] do
    member do
      get :line_items
      get 'document'
    end
  end
  
  resources :projects do
    member do
       get :order_lists
       resources :order_lists, only: [:new, :edit, :update]
    end
  end
  
  resources :projects do
    member do
       get :orders
       resources :orders, only: [:new, :edit, :update]
    end
  end
  
  resources :partners
  
  resources :items, only: [:index, :new, :create, :edit, :update, :destroy]
  
  resources :item_categories, only: [:index, :new, :create, :edit, :update, :destroy]
  
  get 'ajax_select', to: 'items#ajax_select', as: 'ajax_select'
  get 'ajax_calc_subtotal', to: 'order_lists#ajax_calc_subtotal', as: 'ajax_calc_subtotal'
  
end

app/models/order_list.rb
class OrderList < ApplicationRecord
  belongs_to :project
  
  validates :name, presence: true, length: { maximum: 50 }
  
  has_many :line_items, dependent: :destroy
  has_many :items, through: :line_items
  
  accepts_nested_attributes_for :line_items, allow_destroy: true
  
end

app/controllers/order_lists_controller.rb
class OrderListsController < ApplicationController
  before_action :require_user_logged_in
  before_action :set_order_list, only: [:show, :edit, :update, :destroy, :copy]
  before_action :set_partners_order_kana, only: [:new, :create, :edit, :update, :copy_set, :copy]
  before_action :set_items_order_kana, only: [:new, :create, :edit, :update, :copy_set, :copy]
  
  def index
  end

  def show
  end

  def new
    @project = Project.find(params[:id])
    @order_list = OrderList.new(project_id: @project.id)
    @order_list.line_items.build
  end
  
  def create
    @order_list = OrderList.new(order_list_params)
    @project = Project.find(order_list_params[:project_id])
    
    if @order_list.save
      flash[:success] = '発注リストを登録しました'
      redirect_to order_lists_project_url(id: @order_list.project_id)
    else
      render :new
    end
  end
  
  def edit
    @project = Project.find(@order_list.project_id)
  end
  
  def update
    @project = Project.find(update_order_list_params[:project_id])
    if @order_list.update(update_order_list_params)
      flash[:success] = '発注リストを編集しました'
      redirect_to order_lists_project_url(id: @order_list.project_id)
    else
      render :edit
    end
  end
  
  def destroy
    @order_list.destroy
    flash[:success] = '発注リストを削除しました'
    redirect_to order_lists_project_url(id: @order_list.project_id)
  end
  
  def copy_set
    @old_order_list =  OrderList.find(params[:id])
    @line_items = @old_order_list.line_items
    @project = Project.find(@old_order_list.project_id)
    @order_list =  OrderList.new(name: @old_order_list.name + "~コピー", project_id: @old_order_list.project_id)
  end
  
  def copy
    @old_order_list =  OrderList.find(params[:id])
    @line_items = @old_order_list.line_items
    @order_list = OrderList.new(order_list_params)
    if @order_list.save
      @line_items.each do |item|
        item.id = nil
        item.order_list_id = @order_list.id
        item = item.attributes.compact
        LineItem.create!(item)
      end
      flash[:success] = '発注リストを複製しました'
      redirect_to order_lists_project_url(@order_list.project_id)
    else
      flash.now[:danger] = '発注リストの複製に失敗しました'
      render :copy_set
    end
  end
  
  def ajax_calc_subtotal
    if params[:value].present?
      @items = Item.where(item_category_id: params[:value])
    else
      @items = Item.all
    end
    
    @target_id = params[:tar_id]
  end
  
  private
  
  def set_order_list
    @order_list = OrderList.find(params[:id])
  end
  
  def order_list_params
    params.require(:order_list).permit(:name, :project_id, line_items_attributes: [:id, :quantity, :delivery_date, :remark, :item_id, :paid, :unit_price, :partner_id])
  end
  
  def update_order_list_params
    params.require(:order_list).permit(:name, :project_id, line_items_attributes: [:id, :quantity, :delivery_date, :remark, :item_id, :paid, :unit_price, :partner_id, :_destroy])
  end
  
  def set_partners_order_kana
    @partners = Partner.order(:kana)
  end
  
  def set_items_order_kana
    @items = Item.order(:kana)
  end
    
end

app/views/order_lists/_form.html.erb
<%= form_for(@order_list) do |f| %>

  <%= render 'shared/error_messages', object: f.object %>

  <% if current_page?(action: 'copy_set') %>
    <div class="form-group">
      <%= f.label :project_id, '顧客' %>
      <%= f.collection_select(:project_id, Project.all, :id, :name, { prompt: "未選択" }, { class: 'form-control' }) %>
    </div>
  <% else %>
    <%= f.hidden_field :project_id, value: @project.id  %>
  <% end %>
  
  <div class="form-group">
    <%= f.label :name, '発注リスト名' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  
  <hr />
  
  <h2>部材登録</h2>
  
  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <% if current_user.root %>
            <th scope="col">object id</th>
          <% end %>
          <th scope="col">部材カテゴリー</th>
          <th scope="col" style="width: 20%;">部材</th>
          <th scope="col">単価</th>
          <th scope="col">数量</th>
          <th scope="col" style="width: 11%;">小計</th>
          <th scope="col">発注先</th>
          <th scope="col">納期</th>
          <th scope="col">備考</th>
          <th scope="col">支払い金額</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody id="detail-association-insertion-point">
        <%= f.fields_for :line_items do |a| %>
        <%= render 'line_item_fields', f: a %>
        <% end %>
      </tbody>
      <script>
        $(document).on('change', '.category-switch', function(){
          var lineItemObjectId = $(this).attr('id');
          var value = $(this).val();
          $.ajax({
            type: "GET",
            url: "<%= ajax_select_url%>",
            data: `value=${value}&line_item_object_id=${lineItemObjectId}`
          });
        });
        $(document).on('change', '.quantity-field', function(){
          var tarId = $(this).attr('id');
          var tarQuantity = $(this).val();
          var escapeTarId = tarId.replace(/[ !"#$%&'()*+,.\/:;<=>?@\[\\\]^`{|}~]/g, "\\$&");
          var tarPrice = $('#' + escapeTarId + 'price').val();
          var tarSubTotal = tarPrice * tarQuantity;
          $('#' + escapeTarId + 'subtotal').val(tarSubTotal.toString().replace(/(\d)(?=(\d{3})+$)/g , '$1,'));
        });
      </script>
    </table>
  </div>
  
  <%= link_to_add_association '部材追加', f, :line_items,
    class: 'btn btn-primary add-btn',
    data: {
      association_insertion_node: '#detail-association-insertion-point',
      association_insertion_method: 'append' }
   %>

  <%= f.submit '登録する', class: 'btn btn-primary btn-block' %>
<% end %>

app/views/order_lists/_form_copy.html.erb
<%= form_for(@order_list, url: copy_order_list_path(@old_order_list)) do |f| %>
  <div class="form-group">
    <%= f.label :project_id, '顧客' %>
    <%= f.collection_select(:project_id, Project.all, :id, :name, { prompt: "未選択" }, { class: 'form-control' }) %>
  </div>
  
  <div class="form-group">
    <%= f.label :name, '発注リスト名' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
<% end %>

  <hr />

<%= form_for(@old_order_list) do |f| %>
  <h2>部材リスト</h2>
  
  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <% if current_user.root %>
            <th scope="col">object id</th>
          <% end %>
          <th scope="col">部材</th>
          <th scope="col">数量</th>
          <th scope="col">納期</th>
          <th scope="col">備考</th>
          <th scope="col">支払い金額</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody id="detail-association-insertion-point">
        <%= f.fields_for :line_items do |a| %>
        <tr class="nested-fields">
          <% if current_user.root %>
            <td><%= a.object_name %></td>
          <% end %>
          <td id="item-select-<%= a.object_name %>"><%= a.collection_select(:item_id, Item.all, :id, :name, {}, { class: 'form-control', disabled: true } ) %></td>
          <td><%= a.text_field :quantity, class: 'form-control', readonly: true %></td>
          <td><%= a.text_field :delivery_date, class: 'form-control date-picker', readonly: true %></td>
          <td><%= a.text_field :remark, class: 'form-control', readonly: true %></td>
          <td><%= a.text_field :paid, class: 'form-control', readonly: true %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

<%= link_to '登録する', '', class: 'btn btn-primary btn-block', id: 'submit_button' %>

<script>
  $('#submit_button').click(function(e){
    $('#new_order_list').submit();
  });
</script>

app/views/order_lists/_line_item_fields.erb
<tr class="nested-fields">
  <% if current_user.root %>
    <td><%= f.object_name %></td>
  <% end %>
  <td><%= collection_select(:item_category, :item_category_id, ItemCategory.all, :id, :name, { prompt: "未選択" }, { class: 'form-control category-switch', id: "#{f.object_name}" }) %></td>
  <td id="item-select-<%= f.object_name %>"><%= f.collection_select(:item_id, @items, :id, :name, { prompt: "未選択" }, { class: 'form-control' }) %></td>
  <td><%= f.text_field :unit_price, class: 'form-control unit-price-field', id: "#{f.object_name}-price" %></td>
  <td><%= f.text_field :quantity, class: 'form-control quantity-field', id: "#{f.object_name}-" %></td>
  <td><%= text_field :nouse, f.object_name, { placeholder: (f.object[:unit_price].to_i * f.object[:quantity].to_i).to_s(:delimited), id: "#{f.object_name}-subtotal", class: 'form-control', disabled: true } %></td>
  <td><%= f.collection_select(:partner_id, @partners, :id, :name, { prompt: "未選択" }, { class: 'form-control' }) %></td>
  <td><%= f.text_field :delivery_date, class: 'form-control date-picker' %></td>
  <td><%= f.text_field :remark, class: 'form-control' %></td>
  <td><%= f.text_field :paid, class: 'form-control' %></td>
  <td><%= link_to_remove_association '削除', f, class: 'btn btn-default' %></td>
</tr>

app/views/order_lists/_order_lists.html.erb
  <% if order_lists.any? %>
    <div class="table-responsive">
      <table class="table">
        <thead>
          <tr>
            <% if current_user.root %>
              <th>ID</th>
            <% end %>
            <th>発注リスト名</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
        <% order_lists.each do |order_list| %>
          <tr>
            <% if current_user.root %>
              <td><%= order_list.id %></td>
            <% end %>
            <td><%= order_list.name %></td>
            <td>
              <%= link_to '詳細', order_list_path(order_list), class: 'btn btn-secondary' %>
              <%= link_to '編集', edit_order_list_path(order_list), class: 'btn btn-warning' %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
  <% else %>
    <p>発注はありません</p>
  <% end %>

app/views/order_lists/copy.html.erb
<h1><%= @project.name %> 邸の発注リスト原案を作る</h1>

<section>
  <%= render 'form' %>
</section>

app/views/order_lists/copy_set.html.erb
<h1><%= @project.name %> 邸の発注リスト原案を作る</h1>

<section>
  <%= render 'form_copy' %>
</section>

app/views/order_lists/destroy.html.erb
<h1>OrderLists#destroy</h1>
<p>Find me in app/views/order_lists/destroy.html.erb</p>

app/views/order_lists/edit.html.erb
<h1><%= @project.name %> 邸の発注リスト編集</h1>
<section>
  <%= render 'form' %>
</section>

app/views/order_lists/index.html.erb
<h1>OrderLists#index</h1>
<p>Find me in app/views/order_lists/index.html.erb</p>

app/views/order_lists/new.html.erb
<h1><%= @project.name %> 邸の発注リスト登録</h1>
<section>
  <%= render 'form' %>
</section>

app/views/order_lists/show.html.erb
<h1><%= @order_list.project.name %>の<%= @order_list.name %>の詳細</h1>
<section>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th scope="col">項目</th>
        <th scope="col">内容</th>
      </tr>
    </thead>
    <tbody>
      <% if current_user.root %>
        <tr>
          <th scope="row">id</th>
          <td><%= @order_list.id %></td>
        </tr>
      <% end %>
      <tr>
        <th scope="row">発注名称</th></th>
        <td><%= @order_list.name %></td>
      </tr>
      <tr>
        <th scope="row">発注合計</th>
        <td><%= calc_total(@order_list).to_s(:delimited) %>円</td>
      </tr>
    </tbody>
  </table>
</section>

<section>
  <h2>明細</h2>
  <%= render 'line_items/line_items', line_items: @order_list.line_items %>
</section>

<section>
  <%= link_to 'この顧客の発注管理へ', order_lists_project_path(id: @order_list.project_id), class: 'btn btn-lg btn-secondary' %>
  <%= link_to '編集', edit_order_list_path(@order_list), class: 'btn btn-lg btn-warning' %>
  <%= link_to '削除', @order_list, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: 'btn btn-lg btn-danger' %>
  <%= link_to '複製', copy_set_order_list_path(@order_list), class: 'btn btn-lg btn-warning' %>
</section>

app/views/order_lists/update.html.erb
<h1>OrderLists#update</h1>
<p>Find me in app/views/order_lists/update.html.erb</p>