config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  
  get 'dbmap', to: 'static_pages#dbmap'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get '/order_lists/:id/copy_set', to: 'order_lists#copy_set', as: 'copy_set_order_list'
  post '/order_lists/:id/copy', to: 'order_lists#copy', as: 'copy_order_list'
  
  get 'signup', to: 'users#new'
  resources :users
  
  resources :order_lists, only: [:index, :show, :create, :edit, :update, :destroy] do
    member do
      get :line_items
    end
  end
  
  resources :orders, only: [:index, :show, :create, :edit, :update, :destroy] do
    member do
      get :line_items
      get 'document'
    end
  end
  
  resources :projects do
    member do
       get :order_lists
       resources :order_lists, only: [:new, :edit, :update]
    end
  end
  
  resources :projects do
    member do
       get :orders
       resources :orders, only: [:new, :edit, :update]
    end
  end
  
  resources :partners
  
  resources :items, only: [:index, :new, :create, :edit, :update, :destroy]
  
  resources :item_categories, only: [:index, :new, :create, :edit, :update, :destroy]
  
  get 'ajax_select', to: 'items#ajax_select', as: 'ajax_select'
  get 'ajax_calc_subtotal', to: 'order_lists#ajax_calc_subtotal', as: 'ajax_calc_subtotal'
  
end

app/models/partner.rb
class Partner < ApplicationRecord
  has_many :line_items, dependent: :destroy, inverse_of: :partner
  validates :name, presence: true, length: { maximum: 50 }
  validates :kana, presence: true, length: { maximum: 50 }
end

app/controllers/partners_controller.rb
class PartnersController < ApplicationController
  before_action :require_user_logged_in
  before_action :set_partner, only: [:show, :edit, :update, :destroy]
  
  def index
    @partners = Partner.order('created_at DESC').page(params[:page])
  end

  def show
  end
  
  def new
    @partner = Partner.new
  end

  def create
    @partner = Partner.new(partner_params)
    
    if @partner.save
      flash[:success] = '発注先を登録しました'
      redirect_to @partner
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @partner.update(partner_params)
      flash[:success] = '発注先を編集しました'
      redirect_to @partner
    else
      render :edit
    end
  end
  
  def destroy
    @partner.destroy
    flash[:success] = '発注先を削除しました'
    redirect_to partners_url
  end
  
  private
  
  def set_partner
    @partner = Partner.find(params[:id])
  end
  
  def partner_params
    params.require(:partner).permit(:name, :adress, :phone, :fax, :staff, :staff_phone, :postal_code, :kana)
  end
  
end

app/views/partners/_form.html.erb
<%= form_for(@partner) do |f| %>

  <%= render 'shared/error_messages', object: f.object %>

  <div class="form-group">
    <%= f.label :name, '発注先名' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :kana, 'よみがな' %>
    <%= f.text_field :kana, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :postal_code, '郵便番号' %>
    <%= f.text_field :postal_code, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :adress, '住所' %>
    <%= f.text_field :adress, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :phone, '電話番号' %>
    <%= f.text_field :phone, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :fax, 'FAX番号' %>
    <%= f.text_field :fax, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :staff, '担当者' %>
    <%= f.text_field :staff, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :staff_phone, '担当者携帯電話番号' %>
    <%= f.text_field :staff_phone, class: 'form-control' %>
  </div>
  
  <%= f.submit '登録する', class: 'btn btn-primary btn-block' %>
<% end %>

app/views/partners/create.html.erb
<h1>Partners#create</h1>
<p>Find me in app/views/partners/create.html.erb</p>

app/views/partners/edit.html.erb
<h1>発注先編集</h1>
<section>
  <%= render 'form' %>
</section>

app/views/partners/index.html.erb
<h1>発注先一覧</h1>

<section>
  <%= link_to '新規発注先登録', new_partner_path, class: 'btn btn-lg btn-primary' %>
</section>

<hr />

<section>
  <% if @partners.any? %>
    <div class="table-responsive">
      <table class="table">
        <thead>
          <tr>
            <% if current_user.root %>
              <th>ID</th>
            <% end %>
            <th>発注先名</th>
            <th>担当者</th>
            <th>オーダーリスト内の部材数</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
        <% @partners.each do |partner| %>
          <tr>
            <% if current_user.root %>
              <td><%= partner.id %></td>
            <% end %>
            <td><%= link_to partner.name, partner_path(partner) %></td>
            <td><%= partner.staff %></td>
            <td><%= LineItem.where(partner_id: partner.id).count %></td>
            <td>
              <%= link_to '詳細', partner_path(partner), class: 'btn btn-secondary' %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
    <%= paginate @partners %>
  <% else %>
    <p>発注先はまだありません</p>
  <% end %>
</section>

app/views/partners/new.html.erb
<h1>新規発注先登録</h1>
<section>
  <%= render 'form' %>
</section>

app/views/partners/show.html.erb
<h1><%= @partner.name %>の詳細</h1>
<section>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th scope="col">項目</th>
        <th scope="col">内容</th>
      </tr>
    </thead>
    <tbody>
      <% if current_user.root %>
        <tr>
          <th scope="row">id</th>
          <td><%= @partner.id %></td>
        </tr>
      <% end %>
      <tr>
        <th scope="row">発注先名</th>
        <td><%= @partner.name %></td>
      </tr>
      <tr>
        <th scope="row">読み仮名</th>
        <td><%= @partner.kana %></td>
      </tr>
      <tr>
        <th scope="row">郵便番号</th>
        <td><%= @partner.postal_code %></td>
      </tr>
      <tr>
        <th scope="row">住所</th>
        <td><%= @partner.adress %></td>
      </tr>
      <tr>
        <th scope="row">電話番号</th>
        <td><%= @partner.phone %></td>
      </tr>
      <tr>
        <th scope="row">FAX番号</th>
        <td><%= @partner.fax %></td>
      </tr>
      <tr>
        <th scope="row">担当者</th>
        <td><%= @partner.staff %></td>
      </tr>
      <tr>
        <th scope="row">担当者携帯電話番号</th>
        <td><%= @partner.staff_phone %></td>
      </tr>
    </tbody>
  </table>
</section>

<section>
  <%= link_to '発注先一覧へ', partners_path, class: 'btn btn-lg btn-secondary' %>
  <%= link_to '編集', edit_partner_path(@partner), class: 'btn btn-lg btn-warning' %>
  <%= link_to '削除', @partner, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: 'btn btn-lg btn-danger' %>
</section>