config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  
  get 'dbmap', to: 'static_pages#dbmap'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get '/order_lists/:id/copy_set', to: 'order_lists#copy_set', as: 'copy_set_order_list'
  post '/order_lists/:id/copy', to: 'order_lists#copy', as: 'copy_order_list'
  
  get 'signup', to: 'users#new'
  resources :users
  
  resources :order_lists, only: [:index, :show, :create, :edit, :update, :destroy] do
    member do
      get :line_items
    end
  end
  
  resources :orders, only: [:index, :show, :create, :edit, :update, :destroy] do
    member do
      get :line_items
      get 'document'
    end
  end
  
  resources :projects do
    member do
       get :order_lists
       resources :order_lists, only: [:new, :edit, :update]
    end
  end
  
  resources :projects do
    member do
       get :orders
       resources :orders, only: [:new, :edit, :update]
    end
  end
  
  resources :partners
  
  resources :items, only: [:index, :new, :create, :edit, :update, :destroy]
  
  resources :item_categories, only: [:index, :new, :create, :edit, :update, :destroy]
  
  get 'ajax_select', to: 'items#ajax_select', as: 'ajax_select'
  get 'ajax_calc_subtotal', to: 'order_lists#ajax_calc_subtotal', as: 'ajax_calc_subtotal'
  
end

app/models/project.rb
class Project < ApplicationRecord
  
  belongs_to :user
  
  validates :user_id, presence: true
  validates :name, presence: true, length: { maximum: 50 }
  validates :recipt, presence: true, length: { maximum: 18 }, numericality: true
  
  has_many :order_lists, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :line_items, through: :order_lists
  
  after_initialize :set_default_value
  
  def set_default_value
    self.recipt ||= 0
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :require_user_logged_in
  before_action :set_project, only: [:show, :edit, :update, :destroy, :orders, :order_lists]
  
  def index
    @projects = Project.order('created_at DESC').page(params[:page])
  end
  
  def show
  end
  
  def new
    @project = Project.new
  end

  def create
    @project = current_user.projects.build(project_params)
    
    if @project.save
      flash[:success] = '顧客登録しました'
      redirect_to @project
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @project.update(project_params)
      flash[:success] = '顧客を編集しました'
      redirect_to @project
    else
      render :edit
    end
  end
  
  def destroy
    @project.destroy
    flash[:success] = '顧客を削除しました'
    redirect_to projects_url
  end
  
  def orders
  end
  
  def order_lists
  end
  
  private
  
  def set_project
    @project = Project.find(params[:id])
  end
  
  def project_params
    params.require(:project).permit(:code, :name, :current_postal_code, :postal_code, :adress, :current_adress, :phone, :current_phone, :owner_phone, :mrs_phone, :remark, :recipt, :contract_date, :finish_date)
  end
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>

  <%= render 'shared/error_messages', object: f.object %>

  <div class="form-group">
    <%= f.label :code, '顧客番号' %>
    <%= f.text_field :code, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :name, '顧客名' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :current_postal_code, '現郵便番号' %>
    <%= f.text_field :current_postal_code, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :current_adress, '現住所' %>
    <%= f.text_field :current_adress, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :current_phone, '現固定番号' %>
    <%= f.text_field :current_phone, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :owner_phone, 'ご主人携帯電話番号' %>
    <%= f.text_field :owner_phone, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :mrs_phone, '奥様携帯番号' %>
    <%= f.text_field :mrs_phone, class: 'form-control' %>
  </div>
  
  <hr />
  
  <div class="form-group">
    <%= f.label :postal_code, '建築地郵便番号' %>
    <%= f.text_field :postal_code, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :adress, '建築地住所' %>
    <%= f.text_field :adress, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :phone, '建築地固定電話' %>
    <%= f.text_field :phone, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :remark, '備考' %>
    <%= f.text_area :remark, class: 'form-control', size: '20x6' %>
  </div>
  
  <div class="form-group">
    <%= f.label :recipt, '売り上げ' %>
    <%= f.text_field :recipt, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :contract_date, '契約日' %>
    <%= f.text_field :contract_date, class: 'form-control date-picker' %>
  </div>
  
  <div class="form-group">
    <%= f.label :finish_date, '引渡日' %>
    <%= f.text_field :finish_date, class: 'form-control date-picker' %>
  </div>

  <%= f.submit '登録する', class: 'btn btn-primary btn-block' %>
<% end %>

app/views/projects/edit.html.erb
<h1>顧客編集</h1>
<section>
  <%= render 'form' %>
</section>

app/views/projects/index.html.erb
<h1>顧客一覧</h1>

<section>
  <%= link_to '新規顧客登録', new_project_path, class: 'btn btn-lg btn-primary' %>
</section>

<hr />

<section>
  <% if @projects.any? %>
    <div class="table-responsive">
      <table class="table">
        <thead>
          <tr>
            <% if current_user.root %>
              <th>ID</th>
            <% end %>
            <th>顧客番号</th>
            <th>顧客名</th>
            <th>建築地住所</th>
            <th>発注書数</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
        <% @projects.each do |project| %>
          <tr>
            <% if current_user.root %>
              <td><%= project.id %></td>
            <% end %>
            <td><%= project.code %></td>
            <td><%= link_to project.name + ' 邸', project_path(project) %></td>
            <td><%= project.adress %></td>
            <td><%= project.orders.count %></td>
            <td>
              <%= link_to '発注管理', order_lists_project_path(project.id), class: 'btn btn-success' %>
              <%= link_to '詳細', project_path(project), class: 'btn btn-secondary' %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
    <%= paginate @projects %>
  <% else %>
    <p>顧客はまだありません</p>
  <% end %>
</section>

app/views/projects/new.html.erb
<h1>新規顧客登録</h1>
<section>
  <%= form_for(@project) do |f| %>
    <div class="form-group">
      <%= f.label :name, '顧客名' %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    
    <div class="form-group">
      <%= f.label :current_postal_code, '現郵便番号' %>
      <%= f.text_field :current_postal_code, class: 'form-control' %>
    </div>
    
    <div class="form-group">
      <%= f.label :current_adress, '現住所' %>
      <%= f.text_field :current_adress, class: 'form-control' %>
    </div>
    
    <div class="form-group">
      <%= f.label :current_phone, '現固定番号' %>
      <%= f.text_field :current_phone, class: 'form-control' %>
    </div>
    
    <div class="form-group">
      <%= f.label :adress, '建築地住所' %>
      <%= f.text_field :adress, class: 'form-control' %>
    </div>
    
    <div class="form-group">
      <%= f.label :phone, '建築地固定電話' %>
      <%= f.text_field :phone, class: 'form-control' %>
    </div>
    
    <div class="form-group">
      <%= f.label :owner_phone, 'ご主人携帯電話番号' %>
      <%= f.text_field :owner_phone, class: 'form-control' %>
    </div>

    <%= f.submit '登録する', class: 'btn btn-primary btn-block' %>
  <% end %>
</section>

app/views/projects/order_lists.html.erb
<h1><%= @project.name %> 邸の発注管理</h1>

<h2>発注リスト一覧</h2>

<section>
  <%= render 'order_lists/order_lists', order_lists: @project.order_lists %>
  <%= link_to '発注リスト新規作成', new_order_list_path(@project.id), class: 'btn btn-lg btn-primary light-blue' %>
</section>

<h2>発注書一覧</h2>

<section>
  <%= render 'orders/orders', orders: @project.orders %>
  <%= link_to '今回の発注', new_order_path(@project.id), class: 'btn btn-lg btn-primary' %>
</section>

<h2>発注部材一覧</h2>
<section>
  <%= render 'line_items/line_items', line_items: @project.line_items %>
</section>

<section>
  <h2>発注サマリー</h2>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th scope="col">支払い合計金額(税込)</th>
        <th scope="col">売り上げ</th>
        <th scope="col">粗利</th>
        <th scope="col">粗利率</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td class="tAR"><%= (@total = (calc_project_paid_total(@project) * 1.08.rationalize).floor).to_s(:delimited) %>円</td>
        <td class="tAR"><%= @project.recipt.to_s(:delimited) %>円</td>
        <td class="tAR"><%= (@gross_profit = (@project.recipt - @total)).to_s(:delimited) %>円</td>
        <td class="tAR"><%= (@gross_profit.to_f / @project.recipt.to_f) * 100 %>%</td>
      </tr>
    </tbody>
  </table>
</section>

<section>
  <h2>発注金額</h2>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th scope="col">項目</th>
        <th scope="col">内容</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">発注合計</th>
        <td class="tAR"><%= calc_project_total(@project).to_s(:delimited) %>円</td>
      </tr>
      <tr>
        <th scope="row">発注合計(税込)</th>
        <td class="tAR"><%= (total = (calc_project_total(@project) * 1.08).floor).to_s(:delimited) %>円</td>
      </tr>
      <tr>
        <th scope="row">値引き合計</th>
        <td class="tAR"><span style="color: red;">-<%= (discount = calc_project_discount(@project)).to_s(:delimited) %>円</span></td>
      </tr>
      <tr>
        <th scope="row">値引き後発注合計(税込)</th>
        <td class="tAR"><%= (total - discount).to_s(:delimited) %>円</span></td>
      </tr>
      <tr>
        <th scope="row">支払合計</th>
        <td class="tAR"><%= calc_project_paid_total(@project).to_s(:delimited) %>円</td>
      </tr>
    </tbody>
  </table>
</section>

app/views/projects/orders.html.erb
<h1><%= @project.name %> 邸の発注書</h1>

<h2>発注書一覧</h2>

<section>
  <%= render 'orders/orders', orders: @project.orders %>
</section>

<section>
  <%= link_to '発注書新規作成', new_order_path(@project.id), class: 'btn btn-lg btn-primary' %>
</section>

app/views/projects/show.html.erb
<h1><%= @project.name %> 邸の詳細</h1>
<section>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th scope="col">項目</th>
        <th scope="col">内容</th>
      </tr>
    </thead>
    <tbody>
      <% if current_user.root %>
        <tr>
          <th scope="row">id</th>
          <td><%= @project.id %></td>
        </tr>
      <% end %>
      <tr>
        <th scope="row">顧名</th>
        <td><%= @project.name %></td>
      </tr>
      <tr>
        <th scope="row">現郵便番号</th>
        <td><%= @project.current_postal_code %></td>
      </tr>
      <tr>
        <th scope="row">現住所</th>
        <td><%= @project.current_adress %></td>
      </tr>
      <tr>
        <th scope="row">現固定番号</th>
        <td><%= @project.current_phone %></td>
      </tr>
      <tr>
        <th scope="row">建築地郵便番号</th>
        <td><%= @project.postal_code %></td>
      </tr>
      <tr>
        <th scope="row">建築地住所</th>
        <td><%= @project.adress %></td>
      </tr>
      <tr>
        <th scope="row">建築地固定電話</th>
        <td><%= @project.phone %></td>
      </tr>
      <tr>
        <th scope="row">ご主人携帯電話番号</th>
        <td><%= @project.owner_phone %></td>
      </tr>
      <tr>
        <th scope="row">奥様携帯番号</th>
        <td><%= @project.mrs_phone %></td>
      </tr>
      <tr>
        <th scope="row">備考</th>
        <td><%= @project.remark %></td>
      </tr>
      <tr>
        <th scope="row">売り上げ</th>
        <td><%= @project.recipt.to_s(:delimited) %>円</td>
      </tr>
      <tr>
        <th scope="row">契約日</th>
        <td><%= @project.contract_date %></td>
      </tr>
      <tr>
        <th scope="row">引渡日</th>
        <td><%= @project.finish_date %></td>
      </tr>
    </tbody>
  </table>
</section>

<section>
  <%= link_to '顧客一覧へ', projects_path, class: 'btn btn-lg btn-secondary' %>
  <%= link_to '編集', edit_project_path(@project), class: 'btn btn-lg btn-warning' %>
  <%= link_to '削除', @project, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: 'btn btn-lg btn-danger' %>
</section>