config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  
  get 'dbmap', to: 'static_pages#dbmap'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get '/order_lists/:id/copy_set', to: 'order_lists#copy_set', as: 'copy_set_order_list'
  post '/order_lists/:id/copy', to: 'order_lists#copy', as: 'copy_order_list'
  
  get 'signup', to: 'users#new'
  resources :users
  
  resources :order_lists, only: [:index, :show, :create, :edit, :update, :destroy] do
    member do
      get :line_items
    end
  end
  
  resources :orders, only: [:index, :show, :create, :edit, :update, :destroy] do
    member do
      get :line_items
      get 'document'
    end
  end
  
  resources :projects do
    member do
       get :order_lists
       resources :order_lists, only: [:new, :edit, :update]
    end
  end
  
  resources :projects do
    member do
       get :orders
       resources :orders, only: [:new, :edit, :update]
    end
  end
  
  resources :partners
  
  resources :items, only: [:index, :new, :create, :edit, :update, :destroy]
  
  resources :item_categories, only: [:index, :new, :create, :edit, :update, :destroy]
  
  get 'ajax_select', to: 'items#ajax_select', as: 'ajax_select'
  get 'ajax_calc_subtotal', to: 'order_lists#ajax_calc_subtotal', as: 'ajax_calc_subtotal'
  
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="/">発注書作成システム</a>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <% if logged_in? %>
        <% if current_user.root %>
          <li class="nav-item">
            <%= link_to(content_tag(:i, ' データーベース図', class: 'fa fa-database'), dbmap_path, class: 'nav-link') %>
          </li>
        <% end %>
      <% end %>
      <li class="nav-item">
        <%= link_to(content_tag(:i, ' ユーザー一覧', class: 'fa fa-group'), users_path, class: 'nav-link') %>
      </li>
      <% if logged_in? %>
        <% if current_user.admin %>
          <li class="nav-item">
            <%= link_to(content_tag(:i, ' ユーザー登録', class: 'fa fa-user-plus'), signup_path, class: 'nav-link') %>
          </li>
        <% end %>
      <% end %>
      <li class="nav-item">
        <% if logged_in? %>
          <%= link_to(content_tag(:i, ' ログアウト', class: 'fa fa-sign-out'), logout_path, method: :delete, class: 'nav-link') %>
        <% else %>
          <%= link_to(content_tag(:i, ' ログイン', class: 'fa fa-sign-in'), login_path, class: 'nav-link') %>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/_sidebar.html.erb
<nav class="col-sm-3 col-md-2 d-none d-sm-block bg-light sidebar">
  <ul class="nav nav-pills flex-column">
    <li class="nav-item">
      <% if current_page?(root_path) %>
      <a class="nav-link active" href="/"><i class="fa fa-chevron-right"></i> HOME</a>
      <% else %>
      <a class="nav-link" href="/"><i class="fa fa-chevron-right"></i> HOME</a>
      <% end %>
    </li>
    <%= sidebar_list_items() %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>発注書作成システム</title>
    <%= csrf_meta_tags %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navbar' %>
    </header>

    <div class="container-fluid">
      <div class="row">
      
      <%= render 'layouts/sidebar' %>
      
        <main role="main" class="col-sm-9 ml-sm-auto col-md-10 pt-3">
          <article>
            <%= render 'layouts/flash_messages' %>
            <%= yield %>
          </article>
          <hr />
          <div class="logo"><%= image_tag('sw_logo.jpg', class: 'sw_logo') %></div>
        </main>

      </div><!-- .row -->
    </div><!-- .container-fluid -->
  </body>
  
  
  
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>発注書</title>
    <%= csrf_meta_tags %>
    
    <%#= wicked_pdf_stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= wicked_pdf_javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
<style>
.clear{ clear: both; }
.clearfix{ zoom: 1; }
.clearfix:after{ content: ""; display: table; clear: both; }

html {
  font-family: 'IPAexゴシック', 'IPA Pゴシック', 'ヒラギノ角ゴ ProN W3', 'Hiragino Kaku Gothic ProN', 'メイリオ', Meiryo, 'MS Pゴシック', sans-serif;
}

body{
  font-size: 13px
}

table{
  border-spacing: 0;
  border-collapse: collapse;
}

h1{
  text-align: center;
  border-bottom: 3px double #333;
  padding: 0 0 12px 0;
  margin-bottom: 40px;
}

#documentWrap{
  position: relative;
  min-height: 840px;
}

#documentHeaderWrap{
  margin-bottom: 30px;
}

#documentHeaderLeft{
  float: left;
  width: 50%;
  margin-bottom: 40px;
}

#documentHeaderLeft tr th{
  border: 1px solid #666;
  padding: 6px 8px;
  text-align: left;
  font-weight: normal;
}

#documentHeaderLeft tr td{
  border: 1px solid #666;
  padding: 6px 8px;
  text-align: right;
}

#documentHeaderRight{
  float: right;
  width: 42%;
}

#documentHeaderRight tr td{
  padding: 0 0 0 20px;
}

#documentHeaderRight tr:first-child td{
  padding: 0;
}

#partnerTable{
  margin-bottom: 30px;
  width: 50%;
}

#partnerTable tr th{
  text-align: left;
  font-weight: normal;
  padding: 4px 8px;
}

#partnerTable tr td{
  text-align: right;
  padding: 4px 8px;
}

#orderDetail{
  width: 100%;
  margin-bottom: 30px;
}

#orderDetail tr th{
  padding: 4px 8px;
  border: 1px solid #666;
  background: #ccc;
}

#orderDetail tr td{
  padding: 4px 8px;
  border: 1px solid #666;
}

#documentFooterLeft{
  width: 50%;
  float: left
}

#documentFooterLeft tr th{
  padding: 4px 8px;
  border: 1px solid #666;
  text-align: left;
}

#documentFooterLeft tr td{
  padding: 4px 8px;
  border: 1px solid #666;
}

#documentFooterRight{
  width: 40%;
  float: right;
}

#documentFooterRight tr th{
  padding: 4px 8px;
  border: 1px solid #666;
  text-align: left;
}

#documentFooterRight tr td{
  padding: 4px 8px;
  border: 1px solid #666;
  text-align: right;
}

#documentStamp{
  clear: both;
  position: absolute;
  bottom: -90px;
  right: 0;
}

#documentStamp tr td{
  border: 1px solid #666;
  padding: 30px;
}

.sw_logo_pdf{
  width: 300px;
  height: auto;
  padding-bottom: 10px;
  border-bottom: 2px solid #0f3083;
}



</style>
    
  </head>

  <body>
    <%= yield %>
  </body>
  
</html>